import type { Metadata } from "next";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ClientOnly from "./components/ClientOnly";

export const metadata: Metadata = {
  title: "My Restaurant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div>
          <ClientOnly>
            <CartProvider>
              <Navbar />
              {children}
              <Footer />
            </CartProvider>
          </ClientOnly>
        </div>
      </body>
    </html>
  );
}



